baseURL = "https://ashhhi.github.io/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Ash Blog"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "2 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
authorInfo = "developer, gamer, guitar player"
description="Welcome to my world"
previewCardImagePlacement = "bottom"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "SHI Junshen (ASH)"
  email = "shijunshen424@gmail.com"
  bilibili = "497774849?spm_id_from=333.1007.0.0"
  telegram = "ashsjs424"

  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #threads = "username"
  #linkedin = "username"
  github = "ashhhi"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #website = "https://binovarghese.com/"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

#[[menu.main]]
#    name = "Notes"
#    url = "/notes/"
#    weight = 2

[[menu.main]]
    name = "Journals"
    url = "/journals/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4



